jobs:
  build:
    continue-on-error: false
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 100
    - continue-on-error: true
      name: Setup Environment
      run: 'echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

        echo "PMD_CI_SCRIPTS_URL=https://raw.githubusercontent.com/pmd/build-tools/25/scripts"
        >> $GITHUB_ENV

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PMD_CI_SECRET_PASSPHRASE: ${{ secrets.PMD_CI_SECRET_PASSPHRASE }}
      name: Sync
      run: .ci/git-repo-sync.sh
      shell: bash
name: git-repo-sync
on:
  repository_dispatch:
    types: trigger-ga___git-repo-sync.yml
permissions:
  contents: read
